target('1.2.hello_window_clear')
    add_files("./**.cpp")
    add_packages("opengl", "glfw", "glad", "glm", "assimp", "stb")
    add_deps("ht")
    after_build(function (target)
        os.cp("$(projectdir)/asset", target:targetdir())
    end)